### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by AssJoke** [Jinwei1209/LARO-QSM#1]
hi, thanks for your share!
I wonder if you can offer us the dataset or just share a sample so that we can review your experiment. I just want to use it only for the study and research.
Looking forward to your reply, thanks!

**Comment by Jinwei1209** [comment]
Hi, sure I can share the data with you. Please send me an email regarding dataset sharing. My email address is jz853@cornell.edu.

**Comment by Jinwei1209** [comment]
.
